os:
  - linux

language: php

php:
  - "7.2"

services:
  - postgresql

before_script:
  - cp .env.travis .env
  - psql -c 'create database sandbox;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:secret --force
  - php artisan migrate

script:
  - vendor/bin/phpunit
